version: '3.4'

services:
 main-api:
  build:
   context: ./src/main-api/
   dockerfile: Dockerfile
  ports:
   - "5000:80" 
  environment:
   - ConnectionString=mongodb://${MongoDbUser}:${MongoDbPassword}@mainDb:27017
   - DatabaseName=appData
  depends_on:
   - mainDb

 auth-api:
  build:
   context: ./src/auth-api/
   dockerfile: Dockerfile
  ports:
   - "5050:80"
  environment:
   - ConnectionStrings__DefaultConnection=Host=authDb;Username=${PostgresUser};Password=${PostgresPassword};Database=AuthDb
   - JwtSettings__Issuer=${JwtSettingsIssuer}
   - JwtSettings__Audience=${JwtSettingsAudience}
   - JwtSettings__Key=${JwtSettingsKey}
  depends_on:
   - authDb

 mainDb:
  image: mongo
  volumes:
   - mongodbdata:/data/db
  environment:
   - MONGO_INITDB_ROOT_USERNAME=${MongoDbUser}
   - MONGO_INITDB_ROOT_PASSWORD=${MongoDbPassword}

 authDb:
  image: postgres
  volumes:
   - postgresqldata:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=${PostgresUser}
   - POSTGRES_PASSWORD=${PostgresPassword}
   - JwtSettings__Issuer=${JwtSettingsIssuer}
   - JwtSettings__Audience=${JwtSettingsAudience}
   - JwtSettings__Key=${JwtSettingsKey}


volumes:
 mongodbdata:
 postgresqldata: