# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
# AUTH
  build_auth_api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies for Auth-Api
      run: dotnet restore src/auth-api/Auth-Api.sln
    - name: Build Auth-Api
      run: dotnet build src/auth-api/Auth-Api.sln --no-restore
    # - name: test Auth-Api
    # run: dotnet test --no-build --verbosity normal
#Main
  build_Main_api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies for PeakForm
      run: dotnet restore src/main-api/PeakForm.sln
    - name: Build PeakForm
      run: dotnet build src/main-api/PeakForm.sln --no-restore
    - name: test PeakForm
      run: dotnet test src/main-api/PeakForm.sln --no-build --verbosity normal      
